[phases.setup]
nixPkgs = ["openjdk17", "python3", "pip"] # Ajusta la versi√≥n de JDK si usas otra (ej. openjdk11)

[phases.build]
cmds = ["./mvnw clean install", "pip install -r requirements.txt"] # Si tienes dependencias de Python